export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL";

export const GET_PRODUCT_DETAIL_REQUEST = "GET_PRODUCT_DETAIL_REQUEST";
export const GET_PRODUCT_DETAIL_SUCCESS = "GET_PRODUCT_DETAIL_SUCCESS";
export const GET_PRODUCT_DETAIL_FAIL = "GET_PRODUCT_DETAIL_FAIL";
export const GET_PRODUCT_DETAIL_RESET = "GET_PRODUCT_DETAIL_RESET";

export const GET_PRODUCT_CATEGORY_REQUEST = "GET_PRODUCT_CATEGORY_REQUEST"
export const GET_PRODUCT_CATEGORY_SUCCESS = "GET_PRODUCT_CATEGORY_SUCCESS"
export const GET_PRODUCT_CATEGORY_FAIL = "GET_PRODUCT_CATEGORY_FAIL"

export const ADD_TO_CART = "ADD_TO_CART"
export const ADD_TO_CART_ERROR = "ADD_TO_CART_ERROR"

export const REMOVE_FROM_CART = "REMOVE_FROM_CART"

export const INC_QUANTITY = "INC_QUANTITY"
export const DEC_QUANTITY = "DEC_QUANTITY"

export const EMPTY_CART = "EMPTY_CART";